const CANONICAL_TRADES = [
  'Electrical',
  'Plumbing',
  'HVAC',
  'Fire Protection / Sprinkler',
  'Low Voltage',
  'Concrete',
  'Concrete Flatwork',
  'Masonry',
  'Steel / Structural Steel',
  'Framing (wood)',
  'Framing (metal stud)',
  'Roofing',
  'Waterproofing',
  'Insulation',
  'Drywall',
  'Acoustic Ceilings',
  'Flooring (hard surface)',
  'Flooring (carpet)',
  'Tile',
  'Paint',
  'Wall Coverings',
  'Millwork',
  'Casework',
  'Doors & Hardware',
  'Glass & Glazing',
  'Specialties',
  'Demolition',
  'Site Work / Earthwork',
  'Landscaping',
  'Asphalt / Paving',
  'Site Utilities',
  'Kitchen Equipment',
  'Appliances',
  'Elevators / Lifts',
  'Signage',
  'General Conditions',
  'Other',
];

const CANONICAL_TRADES_SET = new Set(CANONICAL_TRADES);

function isValidTrade(trade) {
  return CANONICAL_TRADES_SET.has(trade);
}

const TRADE_MIGRATION_MAP = {
  'electric': 'Electrical',
  'electrical': 'Electrical',
  'electrician': 'Electrical',
  'plumber': 'Plumbing',
  'plumbing': 'Plumbing',
  'hvac': 'HVAC',
  'heating': 'HVAC',
  'air conditioning': 'HVAC',
  'mechanical': 'HVAC',
  'fire protection': 'Fire Protection / Sprinkler',
  'fire sprinkler': 'Fire Protection / Sprinkler',
  'sprinkler': 'Fire Protection / Sprinkler',
  'low voltage': 'Low Voltage',
  'low-voltage': 'Low Voltage',
  'data/comm': 'Low Voltage',
  'data comm': 'Low Voltage',
  'telecom': 'Low Voltage',
  'concrete': 'Concrete',
  'concrete flatwork': 'Concrete Flatwork',
  'flatwork': 'Concrete Flatwork',
  'masonry': 'Masonry',
  'mason': 'Masonry',
  'brick': 'Masonry',
  'steel': 'Steel / Structural Steel',
  'structural steel': 'Steel / Structural Steel',
  'iron work': 'Steel / Structural Steel',
  'ironwork': 'Steel / Structural Steel',
  'framing': 'Framing (wood)',
  'wood framing': 'Framing (wood)',
  'framing (wood)': 'Framing (wood)',
  'metal stud': 'Framing (metal stud)',
  'metal framing': 'Framing (metal stud)',
  'framing (metal stud)': 'Framing (metal stud)',
  'framing (metal)': 'Framing (metal stud)',
  'roofing': 'Roofing',
  'roofer': 'Roofing',
  'waterproofing': 'Waterproofing',
  'insulation': 'Insulation',
  'drywall': 'Drywall',
  'sheetrock': 'Drywall',
  'acoustic ceilings': 'Acoustic Ceilings',
  'acoustic ceiling': 'Acoustic Ceilings',
  'ceiling': 'Acoustic Ceilings',
  'ceilings': 'Acoustic Ceilings',
  'flooring': 'Flooring (hard surface)',
  'flooring (hard surface)': 'Flooring (hard surface)',
  'hard surface flooring': 'Flooring (hard surface)',
  'tile flooring': 'Flooring (hard surface)',
  'carpet': 'Flooring (carpet)',
  'flooring (carpet)': 'Flooring (carpet)',
  'carpeting': 'Flooring (carpet)',
  'tile': 'Tile',
  'paint': 'Paint',
  'painter': 'Paint',
  'painting': 'Paint',
  'wall coverings': 'Wall Coverings',
  'wallpaper': 'Wall Coverings',
  'millwork': 'Millwork',
  'finish carpentry': 'Millwork',
  'casework': 'Casework',
  'cabinetry': 'Casework',
  'cabinets': 'Casework',
  'doors & hardware': 'Doors & Hardware',
  'doors and hardware': 'Doors & Hardware',
  'doors': 'Doors & Hardware',
  'hardware': 'Doors & Hardware',
  'glass & glazing': 'Glass & Glazing',
  'glass and glazing': 'Glass & Glazing',
  'glass': 'Glass & Glazing',
  'glazing': 'Glass & Glazing',
  'specialties': 'Specialties',
  'demolition': 'Demolition',
  'demo': 'Demolition',
  'site work': 'Site Work / Earthwork',
  'sitework': 'Site Work / Earthwork',
  'earthwork': 'Site Work / Earthwork',
  'excavation': 'Site Work / Earthwork',
  'grading': 'Site Work / Earthwork',
  'landscaping': 'Landscaping',
  'landscape': 'Landscaping',
  'asphalt': 'Asphalt / Paving',
  'paving': 'Asphalt / Paving',
  'asphalt / paving': 'Asphalt / Paving',
  'site utilities': 'Site Utilities',
  'utilities': 'Site Utilities',
  'kitchen equipment': 'Kitchen Equipment',
  'kitchen': 'Kitchen Equipment',
  'appliances': 'Appliances',
  'appliance': 'Appliances',
  'elevators': 'Elevators / Lifts',
  'elevator': 'Elevators / Lifts',
  'lifts': 'Elevators / Lifts',
  'signage': 'Signage',
  'signs': 'Signage',
  'general conditions': 'General Conditions',
  'gc': 'General Conditions',
  'general': 'General Conditions',
  'other': 'Other',
};

function mapTradeToCanonical(trade) {
  if (!trade) return null;
  const trimmed = trade.trim();
  if (CANONICAL_TRADES_SET.has(trimmed)) return trimmed;
  const mapped = TRADE_MIGRATION_MAP[trimmed.toLowerCase()];
  return mapped || null;
}

module.exports = {
  CANONICAL_TRADES,
  CANONICAL_TRADES_SET,
  isValidTrade,
  TRADE_MIGRATION_MAP,
  mapTradeToCanonical,
};
