export const CANONICAL_TRADES = [
  'Electrical',
  'Plumbing',
  'HVAC',
  'Fire Protection / Sprinkler',
  'Low Voltage',
  'Concrete',
  'Concrete Flatwork',
  'Masonry',
  'Steel / Structural Steel',
  'Framing (wood)',
  'Framing (metal stud)',
  'Roofing',
  'Waterproofing',
  'Insulation',
  'Drywall',
  'Acoustic Ceilings',
  'Flooring (hard surface)',
  'Flooring (carpet)',
  'Tile',
  'Paint',
  'Wall Coverings',
  'Millwork',
  'Casework',
  'Doors & Hardware',
  'Glass & Glazing',
  'Specialties',
  'Demolition',
  'Site Work / Earthwork',
  'Landscaping',
  'Asphalt / Paving',
  'Site Utilities',
  'Kitchen Equipment',
  'Appliances',
  'Elevators / Lifts',
  'Signage',
  'General Conditions',
  'Other',
];
